[package]
name = "tux-icons"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A library for getting icons in linux"
repository = "https://github.com/Whiskers-Apps/tux-icons"


[dependencies]
dirs = "5.0.1"
walkdir = "2.5.0"
freedesktop-desktop-entry = "0.5.0"